# Generated by Django 4.0.4 on 2022-05-22 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patient')),
                ('booked_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.doctor')),
            ],
        ),
    ]
