# Generated by Django 4.0.4 on 2022-05-22 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0003_alter_appointment_booked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='booked_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.doctor'),
        ),
    ]
