# Generated by Django 4.0.1 on 2022-06-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_appointment_booked_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='booked_by',
            new_name='booked_by_name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='booked_for',
            new_name='booked_for_dr_name',
        ),
    ]
