# Generated by Django 4.0.1 on 2022-06-16 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_rename_booked_by_appointment_booked_by_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 16, 13, 40, 53, 247439)),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='speciality',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 6, 16, 13, 40, 53, 247439)),
        ),
    ]
